spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:43306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: wj40201@gmail.com
    password: qsacpfkadozuiwif
    properties:
      mail:
        smtp:
          starttls:
            enable: true
